# Generated by Django 4.0.1 on 2023-08-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('sobrenome', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
